# [dbo].[cargos]

In [0]:
USE [prueba]
GO

In [0]:
/****** Object:  Table [dbo].[cargos]    Script Date: 25/1/2024 12:08:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[cargos](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[created_at] [datetime] NULL,
	[updated_at] [datetime] NULL,
	[nombre_carg] [nvarchar](255) NOT NULL,
	[codigo] [nvarchar](255) NULL,
	[activo] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[departamentos]

In [0]:
/****** Object:  Table [dbo].[departamentos]    Script Date: 25/1/2024 12:08:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[departamentos](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[created_at] [datetime] NULL,
	[updated_at] [datetime] NULL,
	[nombre_dep] [nvarchar](255) NOT NULL,
	[codigo] [nvarchar](255) NULL,
	[activo] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[failed_jobs]

In [0]:
/****** Object:  Table [dbo].[failed_jobs]    Script Date: 25/1/2024 12:08:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[failed_jobs](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[uuid] [nvarchar](255) NOT NULL,
	[connection] [nvarchar](max) NOT NULL,
	[queue] [nvarchar](max) NOT NULL,
	[payload] [nvarchar](max) NOT NULL,
	[exception] [nvarchar](max) NOT NULL,
	[failed_at] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[migrations]

In [0]:
/****** Object:  Table [dbo].[migrations]    Script Date: 25/1/2024 12:08:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[migrations](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[migration] [nvarchar](255) NOT NULL,
	[batch] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[password_reset_tokens]

In [0]:
/****** Object:  Table [dbo].[password_reset_tokens]    Script Date: 25/1/2024 12:08:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[password_reset_tokens](
	[email] [nvarchar](255) NOT NULL,
	[token] [nvarchar](255) NOT NULL,
	[created_at] [datetime] NULL,
 CONSTRAINT [password_reset_tokens_email_primary] PRIMARY KEY CLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[personal_access_tokens]

In [0]:
/****** Object:  Table [dbo].[personal_access_tokens]    Script Date: 25/1/2024 12:08:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[personal_access_tokens](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[tokenable_type] [nvarchar](255) NOT NULL,
	[tokenable_id] [bigint] NOT NULL,
	[name] [nvarchar](255) NOT NULL,
	[token] [nvarchar](64) NOT NULL,
	[abilities] [nvarchar](max) NULL,
	[last_used_at] [datetime] NULL,
	[expires_at] [datetime] NULL,
	[created_at] [datetime] NULL,
	[updated_at] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[usuarios]

In [0]:
/****** Object:  Table [dbo].[usuarios]    Script Date: 25/1/2024 12:08:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[usuarios](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[usuario] [nvarchar](255) NOT NULL,
	[email] [nvarchar](255) NOT NULL,
	[primerNombre] [nvarchar](255) NOT NULL,
	[segundoNombre] [nvarchar](255) NULL,
	[primerApellido] [nvarchar](255) NOT NULL,
	[segundoApellido] [nvarchar](255) NULL,
	[idDepartamento] [bigint] NOT NULL,
	[idCargo] [bigint] NOT NULL,
	[created_at] [datetime] NULL,
	[updated_at] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[cargos]

In [0]:
SET IDENTITY_INSERT [dbo].[cargos] ON 
INSERT [dbo].[cargos] ([id], [created_at], [updated_at], [nombre_carg], [codigo], [activo]) VALUES (1, NULL, NULL, N'Administrador', N'ADM', 1)
INSERT [dbo].[cargos] ([id], [created_at], [updated_at], [nombre_carg], [codigo], [activo]) VALUES (2, NULL, NULL, N'Desarrollador Frontend', N'DEV-FE', 1)
INSERT [dbo].[cargos] ([id], [created_at], [updated_at], [nombre_carg], [codigo], [activo]) VALUES (3, NULL, NULL, N'Desarrollador Backend', N'DEV-BE', 1)
INSERT [dbo].[cargos] ([id], [created_at], [updated_at], [nombre_carg], [codigo], [activo]) VALUES (4, NULL, NULL, N'Guardia', N'GRD', 1)
SET IDENTITY_INSERT [dbo].[cargos] OFF
GO

# [dbo].[departamentos]

In [0]:
SET IDENTITY_INSERT [dbo].[departamentos] ON 
INSERT [dbo].[departamentos] ([id], [created_at], [updated_at], [nombre_dep], [codigo], [activo]) VALUES (1, NULL, NULL, N'Departamento de Marketing', N'MKT', 1)
INSERT [dbo].[departamentos] ([id], [created_at], [updated_at], [nombre_dep], [codigo], [activo]) VALUES (2, NULL, NULL, N'Departamento de Informatica', N'IT', 1)
INSERT [dbo].[departamentos] ([id], [created_at], [updated_at], [nombre_dep], [codigo], [activo]) VALUES (3, NULL, NULL, N'Departamento de Seguridad', N'SEC', 1)
INSERT [dbo].[departamentos] ([id], [created_at], [updated_at], [nombre_dep], [codigo], [activo]) VALUES (4, NULL, NULL, N'Departamento de Administracion', N'ADM', 1)
SET IDENTITY_INSERT [dbo].[departamentos] OFF
GO

# [dbo].[migrations]

In [0]:
SET IDENTITY_INSERT [dbo].[migrations] ON 
INSERT [dbo].[migrations] ([id], [migration], [batch]) VALUES (20, N'2014_10_12_000000_create_users_table', 1)
INSERT [dbo].[migrations] ([id], [migration], [batch]) VALUES (21, N'2014_10_12_100000_create_password_reset_tokens_table', 1)
INSERT [dbo].[migrations] ([id], [migration], [batch]) VALUES (22, N'2019_08_19_000000_create_failed_jobs_table', 1)
INSERT [dbo].[migrations] ([id], [migration], [batch]) VALUES (23, N'2019_12_14_000001_create_personal_access_tokens_table', 1)
INSERT [dbo].[migrations] ([id], [migration], [batch]) VALUES (24, N'2024_01_24_100222_create_departamentos_table', 1)
INSERT [dbo].[migrations] ([id], [migration], [batch]) VALUES (25, N'2024_01_24_100252_create_cargos_table', 1)
SET IDENTITY_INSERT [dbo].[migrations] OFF
GO

# [dbo].[usuarios]

In [0]:
SET IDENTITY_INSERT [dbo].[usuarios] ON 
INSERT [dbo].[usuarios] ([id], [usuario], [email], [primerNombre], [segundoNombre], [primerApellido], [segundoApellido], [idDepartamento], [idCargo], [created_at], [updated_at]) VALUES (1, N'nombreUsuario1', N'correo1@example.com', N'PrimerNombre1', N'SegundoNombre1', N'PrimerApellido1', N'SegundoApellido1', 1, 1, CAST(N'2024-01-24T14:16:47.743' AS DateTime), CAST(N'2024-01-24T14:16:47.743' AS DateTime))
INSERT [dbo].[usuarios] ([id], [usuario], [email], [primerNombre], [segundoNombre], [primerApellido], [segundoApellido], [idDepartamento], [idCargo], [created_at], [updated_at]) VALUES (2, N'nombreUsuario2', N'correo2@example.com', N'PrimerNombre2', N'SegundoNombre2', N'PrimerApellido2', N'SegundoApellido2', 2, 2, CAST(N'2024-01-24T14:16:47.743' AS DateTime), CAST(N'2024-01-24T14:16:47.743' AS DateTime))
SET IDENTITY_INSERT [dbo].[usuarios] OFF
GO

# [failed_jobs_uuid_unique]

In [0]:
SET ANSI_PADDING ON
GO
/****** Object:  Index [failed_jobs_uuid_unique]    Script Date: 25/1/2024 12:08:12 ******/
CREATE UNIQUE NONCLUSTERED INDEX [failed_jobs_uuid_unique] ON [dbo].[failed_jobs]
(
	[uuid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

# [personal_access_tokens_token_unique]

In [0]:
SET ANSI_PADDING ON
GO
/****** Object:  Index [personal_access_tokens_token_unique]    Script Date: 25/1/2024 12:08:12 ******/
CREATE UNIQUE NONCLUSTERED INDEX [personal_access_tokens_token_unique] ON [dbo].[personal_access_tokens]
(
	[token] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

# [personal_access_tokens_tokenable_type_tokenable_id_index]

In [0]:
SET ANSI_PADDING ON
GO
/****** Object:  Index [personal_access_tokens_tokenable_type_tokenable_id_index]    Script Date: 25/1/2024 12:08:12 ******/
CREATE NONCLUSTERED INDEX [personal_access_tokens_tokenable_type_tokenable_id_index] ON [dbo].[personal_access_tokens]
(
	[tokenable_type] ASC,
	[tokenable_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

# [DF__cargos__activo__06CD04F7]

In [0]:
ALTER TABLE [dbo].[cargos] ADD  DEFAULT ('1') FOR [activo]
GO

# [DF__departame__activ__03F0984C]

In [0]:
ALTER TABLE [dbo].[departamentos] ADD  DEFAULT ('1') FOR [activo]
GO

# [DF__failed_jo__faile__7F2BE32F]

In [0]:
ALTER TABLE [dbo].[failed_jobs] ADD  DEFAULT (getdate()) FOR [failed_at]
GO

# [usuarios_idcargo_foreign]

In [0]:
ALTER TABLE [dbo].[usuarios]  WITH CHECK ADD  CONSTRAINT [usuarios_idcargo_foreign] FOREIGN KEY([idCargo])
REFERENCES [dbo].[cargos] ([id])
GO
ALTER TABLE [dbo].[usuarios] CHECK CONSTRAINT [usuarios_idcargo_foreign]
GO

# [usuarios_iddepartamento_foreign]

In [0]:
ALTER TABLE [dbo].[usuarios]  WITH CHECK ADD  CONSTRAINT [usuarios_iddepartamento_foreign] FOREIGN KEY([idDepartamento])
REFERENCES [dbo].[departamentos] ([id])
GO
ALTER TABLE [dbo].[usuarios] CHECK CONSTRAINT [usuarios_iddepartamento_foreign]
GO